name: Failing Runner 2 (1 minute)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  failing-job-2:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Wait 1 minute then fail
      run: |
        echo "Starting job that will fail after 1 minute..."
        sleep 60
        echo "1 minute passed! Failing now..."
        exit 1

