name: Success Runner 3 (30 seconds)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  success-job-3:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Wait 30 seconds then succeed
      run: |
        echo "Starting job that will succeed after 30 seconds..."
        sleep 30
        echo "30 seconds passed! Job completed successfully!"
        exit 0

