name: Success Runner 1 (3 seconds)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  success-job-1:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Wait 3 seconds then succeed
      run: |
        echo "Starting job that will succeed after 3 seconds..."
        sleep 3
        echo "3 seconds passed! Job completed successfully!"
        exit 0

