name: Success Runner 5 (1:40 minutes)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  success-job-5:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Wait 1:40 minutes then succeed
      run: |
        echo "Starting job that will succeed after 1 minute and 40 seconds..."
        sleep 100
        echo "1 minute and 40 seconds passed! Job completed successfully!"
        exit 0

